/*
 * generated by Xtext
 */
package com.crubier.lil;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LilRuntimeModule extends com.crubier.lil.AbstractLilRuntimeModule {

}
