/*
 * generated by Xtext
 */
package com.crubier.lil.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LilUiModule extends com.crubier.lil.ui.AbstractLilUiModule {
	public LilUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
