/**
 * generated by Xtext
 */
package com.crubier.lil.generator;

import com.crubier.lil.generator.LilGeneratorC;
import com.crubier.lil.generator.LilGeneratorFlattenedLil;
import com.crubier.lil.generator.LilGeneratorJava;
import javax.inject.Inject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class LilGenerator implements IGenerator {
  @Inject
  private LilGeneratorC GeneratorC;
  
  @Inject
  private LilGeneratorJava GeneratorJava;
  
  @Inject
  private LilGeneratorFlattenedLil GeneratorFlattenedLil;
  
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    this.GeneratorFlattenedLil.doGenerate(resource, fsa);
    this.GeneratorC.doGenerate(resource, fsa);
    this.GeneratorJava.doGenerate(resource, fsa);
  }
}
