/*
* generated by Xtext
*/
package com.crubier.lil.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.crubier.lil.services.LilGrammarAccess;

public class LilParser extends AbstractContentAssistParser {
	
	@Inject
	private LilGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser createParser() {
		com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser result = new com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getLilModelAccess().getAlternatives(), "rule__LilModel__Alternatives");
					put(grammarAccess.getActorTypeAccess().getAlternatives(), "rule__ActorType__Alternatives");
					put(grammarAccess.getDataTypeDefinitionAccess().getAlternatives(), "rule__DataTypeDefinition__Alternatives");
					put(grammarAccess.getDataTypeAccess().getAlternatives_0(), "rule__DataType__Alternatives_0");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getAlternatives(), "rule__DataTypeNumberDefinitionSet__Alternatives");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getAlternatives(), "rule__DataTypeTimeDefinitionSet__Alternatives");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getAlternatives_3(), "rule__InteractorTypeDefinition__Alternatives_3");
					put(grammarAccess.getInteractorDataComponentModeAccess().getAlternatives(), "rule__InteractorDataComponentMode__Alternatives");
					put(grammarAccess.getAccessibleEntityAccess().getAlternatives(), "rule__AccessibleEntity__Alternatives");
					put(grammarAccess.getGenericEntityAccess().getAlternatives(), "rule__GenericEntity__Alternatives");
					put(grammarAccess.getEntityAccess().getAlternatives(), "rule__Entity__Alternatives");
					put(grammarAccess.getInteractorSignalReceptionAccess().getAlternatives(), "rule__InteractorSignalReception__Alternatives");
					put(grammarAccess.getInteractorBehaviorCauseAccess().getAlternatives(), "rule__InteractorBehaviorCause__Alternatives");
					put(grammarAccess.getInteractorBehaviorEffectAccess().getAlternatives(), "rule__InteractorBehaviorEffect__Alternatives");
					put(grammarAccess.getExpressionEqualityOpAccess().getAlternatives(), "rule__ExpressionEqualityOp__Alternatives");
					put(grammarAccess.getExpressionCompareOpAccess().getAlternatives(), "rule__ExpressionCompareOp__Alternatives");
					put(grammarAccess.getExpressionOtherOpAccess().getAlternatives(), "rule__ExpressionOtherOp__Alternatives");
					put(grammarAccess.getExpressionAdditionOpAccess().getAlternatives(), "rule__ExpressionAdditionOp__Alternatives");
					put(grammarAccess.getExpressionMultiplicationOpAccess().getAlternatives(), "rule__ExpressionMultiplicationOp__Alternatives");
					put(grammarAccess.getExpressionUnaryAccess().getAlternatives(), "rule__ExpressionUnary__Alternatives");
					put(grammarAccess.getExpressionUnaryOpAccess().getAlternatives(), "rule__ExpressionUnaryOp__Alternatives");
					put(grammarAccess.getExpressionPrimaryAccess().getAlternatives(), "rule__ExpressionPrimary__Alternatives");
					put(grammarAccess.getExpressionLiteralAccess().getAlternatives(), "rule__ExpressionLiteral__Alternatives");
					put(grammarAccess.getExpressionLiteralCollectionAccess().getAlternatives(), "rule__ExpressionLiteralCollection__Alternatives");
					put(grammarAccess.getExpressionFunctionCallBaseAccess().getAlternatives(), "rule__ExpressionFunctionCallBase__Alternatives");
					put(grammarAccess.getLiteralBooleanAccess().getAlternatives_1(), "rule__LiteralBoolean__Alternatives_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives(), "rule__LiteralTime__Alternatives");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_1_5_1(), "rule__LiteralTime__Alternatives_1_5_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_1_6_1(), "rule__LiteralTime__Alternatives_1_6_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_2_4_1(), "rule__LiteralTime__Alternatives_2_4_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_2_5_1(), "rule__LiteralTime__Alternatives_2_5_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_3_3_1(), "rule__LiteralTime__Alternatives_3_3_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_3_4_1(), "rule__LiteralTime__Alternatives_3_4_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_4_2_1(), "rule__LiteralTime__Alternatives_4_2_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_4_3_1(), "rule__LiteralTime__Alternatives_4_3_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_5_1_1(), "rule__LiteralTime__Alternatives_5_1_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_5_2_1(), "rule__LiteralTime__Alternatives_5_2_1");
					put(grammarAccess.getLiteralTimeAccess().getAlternatives_6_1_1(), "rule__LiteralTime__Alternatives_6_1_1");
					put(grammarAccess.getActorTypeDefinitionAccess().getGroup(), "rule__ActorTypeDefinition__Group__0");
					put(grammarAccess.getActorTypeAccess().getGroup_0(), "rule__ActorType__Group_0__0");
					put(grammarAccess.getActorTypeAccess().getGroup_1(), "rule__ActorType__Group_1__0");
					put(grammarAccess.getActorTypeAccess().getGroup_2(), "rule__ActorType__Group_2__0");
					put(grammarAccess.getActorInstanceDeclarationAccess().getGroup(), "rule__ActorInstanceDeclaration__Group__0");
					put(grammarAccess.getDataTypeDefinitionAccess().getGroup_0(), "rule__DataTypeDefinition__Group_0__0");
					put(grammarAccess.getDataTypeDefinitionAccess().getGroup_1(), "rule__DataTypeDefinition__Group_1__0");
					put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_0(), "rule__DataType__Group_0_0__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_1(), "rule__DataType__Group_0_1__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_1_2(), "rule__DataType__Group_0_1_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_2(), "rule__DataType__Group_0_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_2_2(), "rule__DataType__Group_0_2_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_3(), "rule__DataType__Group_0_3__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_3_2(), "rule__DataType__Group_0_3_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_4(), "rule__DataType__Group_0_4__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_4_2(), "rule__DataType__Group_0_4_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_5(), "rule__DataType__Group_0_5__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_5_2(), "rule__DataType__Group_0_5_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_0_6(), "rule__DataType__Group_0_6__0");
					put(grammarAccess.getDataTypeAccess().getGroup_1(), "rule__DataType__Group_1__0");
					put(grammarAccess.getDataTypeAccess().getGroup_1_0(), "rule__DataType__Group_1_0__0");
					put(grammarAccess.getDataTypeAccess().getGroup_2(), "rule__DataType__Group_2__0");
					put(grammarAccess.getDataTypeAccess().getGroup_2_0(), "rule__DataType__Group_2_0__0");
					put(grammarAccess.getDataTypeAccess().getGroup_3(), "rule__DataType__Group_3__0");
					put(grammarAccess.getDataTypeAccess().getGroup_3_0(), "rule__DataType__Group_3_0__0");
					put(grammarAccess.getDataTypeAccess().getGroup_4(), "rule__DataType__Group_4__0");
					put(grammarAccess.getDataTypeAccess().getGroup_4_0(), "rule__DataType__Group_4_0__0");
					put(grammarAccess.getDataTypeSymbolDefinitionSetAccess().getGroup(), "rule__DataTypeSymbolDefinitionSet__Group__0");
					put(grammarAccess.getDataTypeSymbolDefinitionSetAccess().getGroup_2(), "rule__DataTypeSymbolDefinitionSet__Group_2__0");
					put(grammarAccess.getDataTypeSymbolDefinitionSetElementAccess().getGroup(), "rule__DataTypeSymbolDefinitionSetElement__Group__0");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getGroup_0(), "rule__DataTypeNumberDefinitionSet__Group_0__0");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getGroup_0_3(), "rule__DataTypeNumberDefinitionSet__Group_0_3__0");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getGroup_1(), "rule__DataTypeNumberDefinitionSet__Group_1__0");
					put(grammarAccess.getDataTypeTextDefinitionSetAccess().getGroup(), "rule__DataTypeTextDefinitionSet__Group__0");
					put(grammarAccess.getDataTypeTextDefinitionSetAccess().getGroup_3(), "rule__DataTypeTextDefinitionSet__Group_3__0");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getGroup_0(), "rule__DataTypeTimeDefinitionSet__Group_0__0");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getGroup_0_3(), "rule__DataTypeTimeDefinitionSet__Group_0_3__0");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getGroup_1(), "rule__DataTypeTimeDefinitionSet__Group_1__0");
					put(grammarAccess.getDataTypeIdentifierDefinitionSetAccess().getGroup(), "rule__DataTypeIdentifierDefinitionSet__Group__0");
					put(grammarAccess.getDataTypeIdentifierDefinitionSetAccess().getGroup_3(), "rule__DataTypeIdentifierDefinitionSet__Group_3__0");
					put(grammarAccess.getDataInstanceDeclarationAccess().getGroup(), "rule__DataInstanceDeclaration__Group__0");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getGroup(), "rule__InteractorTypeDefinition__Group__0");
					put(grammarAccess.getInteractorActorAccess().getGroup(), "rule__InteractorActor__Group__0");
					put(grammarAccess.getInteractorDataAccess().getGroup(), "rule__InteractorData__Group__0");
					put(grammarAccess.getInteractorDataAccess().getGroup_4(), "rule__InteractorData__Group_4__0");
					put(grammarAccess.getInteractorDataAccess().getGroup_5(), "rule__InteractorData__Group_5__0");
					put(grammarAccess.getInteractorSignalAliasAccess().getGroup(), "rule__InteractorSignalAlias__Group__0");
					put(grammarAccess.getInteractorSignalAliasAccess().getGroup_1(), "rule__InteractorSignalAlias__Group_1__0");
					put(grammarAccess.getInteractorComponentAccess().getGroup(), "rule__InteractorComponent__Group__0");
					put(grammarAccess.getInteractorComponentAccess().getGroup_4(), "rule__InteractorComponent__Group_4__0");
					put(grammarAccess.getInteractorComponentAccess().getGroup_4_2(), "rule__InteractorComponent__Group_4_2__0");
					put(grammarAccess.getActorAliasAccess().getGroup(), "rule__ActorAlias__Group__0");
					put(grammarAccess.getInteractorSignalReceptionAccess().getGroup_0(), "rule__InteractorSignalReception__Group_0__0");
					put(grammarAccess.getInteractorSignalReceptionAccess().getGroup_0_1(), "rule__InteractorSignalReception__Group_0_1__0");
					put(grammarAccess.getInteractorSignalEmissionAccess().getGroup(), "rule__InteractorSignalEmission__Group__0");
					put(grammarAccess.getInteractorSignalEmissionAccess().getGroup_1(), "rule__InteractorSignalEmission__Group_1__0");
					put(grammarAccess.getInteractorBehaviorAccess().getGroup(), "rule__InteractorBehavior__Group__0");
					put(grammarAccess.getInteractorBehaviorOnCauseAccess().getGroup(), "rule__InteractorBehaviorOnCause__Group__0");
					put(grammarAccess.getInteractorBehaviorOnCauseAccess().getGroup_2(), "rule__InteractorBehaviorOnCause__Group_2__0");
					put(grammarAccess.getInteractorBehaviorWhenCauseAccess().getGroup(), "rule__InteractorBehaviorWhenCause__Group__0");
					put(grammarAccess.getInteractorBehaviorWhenCauseAccess().getGroup_2(), "rule__InteractorBehaviorWhenCause__Group_2__0");
					put(grammarAccess.getInteractorBehaviorAlwaysEffectAccess().getGroup(), "rule__InteractorBehaviorAlwaysEffect__Group__0");
					put(grammarAccess.getInteractorBehaviorSetEffectAccess().getGroup(), "rule__InteractorBehaviorSetEffect__Group__0");
					put(grammarAccess.getInteractorBehaviorTriggerEffectAccess().getGroup(), "rule__InteractorBehaviorTriggerEffect__Group__0");
					put(grammarAccess.getExpressionOrAccess().getGroup(), "rule__ExpressionOr__Group__0");
					put(grammarAccess.getExpressionOrAccess().getGroup_1(), "rule__ExpressionOr__Group_1__0");
					put(grammarAccess.getExpressionOrAccess().getGroup_1_0(), "rule__ExpressionOr__Group_1_0__0");
					put(grammarAccess.getExpressionOrAccess().getGroup_1_0_0(), "rule__ExpressionOr__Group_1_0_0__0");
					put(grammarAccess.getExpressionAndAccess().getGroup(), "rule__ExpressionAnd__Group__0");
					put(grammarAccess.getExpressionAndAccess().getGroup_1(), "rule__ExpressionAnd__Group_1__0");
					put(grammarAccess.getExpressionAndAccess().getGroup_1_0(), "rule__ExpressionAnd__Group_1_0__0");
					put(grammarAccess.getExpressionAndAccess().getGroup_1_0_0(), "rule__ExpressionAnd__Group_1_0_0__0");
					put(grammarAccess.getExpressionEqualityAccess().getGroup(), "rule__ExpressionEquality__Group__0");
					put(grammarAccess.getExpressionEqualityAccess().getGroup_1(), "rule__ExpressionEquality__Group_1__0");
					put(grammarAccess.getExpressionEqualityAccess().getGroup_1_0(), "rule__ExpressionEquality__Group_1_0__0");
					put(grammarAccess.getExpressionEqualityAccess().getGroup_1_0_0(), "rule__ExpressionEquality__Group_1_0_0__0");
					put(grammarAccess.getExpressionCompareAccess().getGroup(), "rule__ExpressionCompare__Group__0");
					put(grammarAccess.getExpressionCompareAccess().getGroup_1(), "rule__ExpressionCompare__Group_1__0");
					put(grammarAccess.getExpressionCompareAccess().getGroup_1_0(), "rule__ExpressionCompare__Group_1_0__0");
					put(grammarAccess.getExpressionCompareAccess().getGroup_1_0_0(), "rule__ExpressionCompare__Group_1_0_0__0");
					put(grammarAccess.getExpressionOtherAccess().getGroup(), "rule__ExpressionOther__Group__0");
					put(grammarAccess.getExpressionOtherAccess().getGroup_1(), "rule__ExpressionOther__Group_1__0");
					put(grammarAccess.getExpressionOtherAccess().getGroup_1_0(), "rule__ExpressionOther__Group_1_0__0");
					put(grammarAccess.getExpressionOtherAccess().getGroup_1_0_0(), "rule__ExpressionOther__Group_1_0_0__0");
					put(grammarAccess.getExpressionAdditionAccess().getGroup(), "rule__ExpressionAddition__Group__0");
					put(grammarAccess.getExpressionAdditionAccess().getGroup_1(), "rule__ExpressionAddition__Group_1__0");
					put(grammarAccess.getExpressionAdditionAccess().getGroup_1_0(), "rule__ExpressionAddition__Group_1_0__0");
					put(grammarAccess.getExpressionAdditionAccess().getGroup_1_0_0(), "rule__ExpressionAddition__Group_1_0_0__0");
					put(grammarAccess.getExpressionMultiplicationAccess().getGroup(), "rule__ExpressionMultiplication__Group__0");
					put(grammarAccess.getExpressionMultiplicationAccess().getGroup_1(), "rule__ExpressionMultiplication__Group_1__0");
					put(grammarAccess.getExpressionMultiplicationAccess().getGroup_1_0(), "rule__ExpressionMultiplication__Group_1_0__0");
					put(grammarAccess.getExpressionMultiplicationAccess().getGroup_1_0_0(), "rule__ExpressionMultiplication__Group_1_0_0__0");
					put(grammarAccess.getExpressionUnaryAccess().getGroup_0(), "rule__ExpressionUnary__Group_0__0");
					put(grammarAccess.getExpressionLiteralAccess().getGroup_7(), "rule__ExpressionLiteral__Group_7__0");
					put(grammarAccess.getExpressionLiteralSetAccess().getGroup(), "rule__ExpressionLiteralSet__Group__0");
					put(grammarAccess.getExpressionLiteralSetAccess().getGroup_2(), "rule__ExpressionLiteralSet__Group_2__0");
					put(grammarAccess.getExpressionLiteralSetAccess().getGroup_2_1(), "rule__ExpressionLiteralSet__Group_2_1__0");
					put(grammarAccess.getExpressionLiteralListAccess().getGroup(), "rule__ExpressionLiteralList__Group__0");
					put(grammarAccess.getExpressionLiteralListAccess().getGroup_2(), "rule__ExpressionLiteralList__Group_2__0");
					put(grammarAccess.getExpressionLiteralListAccess().getGroup_2_1(), "rule__ExpressionLiteralList__Group_2_1__0");
					put(grammarAccess.getExpressionParenthesizedAccess().getGroup(), "rule__ExpressionParenthesized__Group__0");
					put(grammarAccess.getExpressionIfAccess().getGroup(), "rule__ExpressionIf__Group__0");
					put(grammarAccess.getExpressionIfAccess().getGroup_6(), "rule__ExpressionIf__Group_6__0");
					put(grammarAccess.getExpressionSwitchAccess().getGroup(), "rule__ExpressionSwitch__Group__0");
					put(grammarAccess.getExpressionSwitchAccess().getGroup_6(), "rule__ExpressionSwitch__Group_6__0");
					put(grammarAccess.getExpressionCaseAccess().getGroup(), "rule__ExpressionCase__Group__0");
					put(grammarAccess.getExpressionForEachAccess().getGroup(), "rule__ExpressionForEach__Group__0");
					put(grammarAccess.getExpressionFunctionCallAccess().getGroup(), "rule__ExpressionFunctionCall__Group__0");
					put(grammarAccess.getExpressionFunctionCallAccess().getGroup_4(), "rule__ExpressionFunctionCall__Group_4__0");
					put(grammarAccess.getLiteralBooleanAccess().getGroup(), "rule__LiteralBoolean__Group__0");
					put(grammarAccess.getLiteralNullAccess().getGroup(), "rule__LiteralNull__Group__0");
					put(grammarAccess.getLiteralNumberAccess().getGroup(), "rule__LiteralNumber__Group__0");
					put(grammarAccess.getLiteralTextAccess().getGroup(), "rule__LiteralText__Group__0");
					put(grammarAccess.getLiteralEnumAccess().getGroup(), "rule__LiteralEnum__Group__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_0(), "rule__LiteralTime__Group_0__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1(), "rule__LiteralTime__Group_1__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1_1(), "rule__LiteralTime__Group_1_1__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1_2(), "rule__LiteralTime__Group_1_2__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1_3(), "rule__LiteralTime__Group_1_3__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1_4(), "rule__LiteralTime__Group_1_4__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1_5(), "rule__LiteralTime__Group_1_5__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_1_6(), "rule__LiteralTime__Group_1_6__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_2(), "rule__LiteralTime__Group_2__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_2_1(), "rule__LiteralTime__Group_2_1__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_2_2(), "rule__LiteralTime__Group_2_2__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_2_3(), "rule__LiteralTime__Group_2_3__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_2_4(), "rule__LiteralTime__Group_2_4__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_2_5(), "rule__LiteralTime__Group_2_5__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_3(), "rule__LiteralTime__Group_3__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_3_1(), "rule__LiteralTime__Group_3_1__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_3_2(), "rule__LiteralTime__Group_3_2__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_3_3(), "rule__LiteralTime__Group_3_3__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_3_4(), "rule__LiteralTime__Group_3_4__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_4(), "rule__LiteralTime__Group_4__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_4_1(), "rule__LiteralTime__Group_4_1__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_4_2(), "rule__LiteralTime__Group_4_2__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_4_3(), "rule__LiteralTime__Group_4_3__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_5(), "rule__LiteralTime__Group_5__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_5_1(), "rule__LiteralTime__Group_5_1__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_5_2(), "rule__LiteralTime__Group_5_2__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_6(), "rule__LiteralTime__Group_6__0");
					put(grammarAccess.getLiteralTimeAccess().getGroup_6_1(), "rule__LiteralTime__Group_6_1__0");
					put(grammarAccess.getNUMBERAccess().getGroup(), "rule__NUMBER__Group__0");
					put(grammarAccess.getNUMBERAccess().getGroup_1(), "rule__NUMBER__Group_1__0");
					put(grammarAccess.getLilModelAccess().getActorTypeAssignment_0(), "rule__LilModel__ActorTypeAssignment_0");
					put(grammarAccess.getLilModelAccess().getDataTypeAssignment_1(), "rule__LilModel__DataTypeAssignment_1");
					put(grammarAccess.getLilModelAccess().getInteractorTypeAssignment_2(), "rule__LilModel__InteractorTypeAssignment_2");
					put(grammarAccess.getActorTypeDefinitionAccess().getNameAssignment_0(), "rule__ActorTypeDefinition__NameAssignment_0");
					put(grammarAccess.getActorTypeDefinitionAccess().getComponentAssignment_3(), "rule__ActorTypeDefinition__ComponentAssignment_3");
					put(grammarAccess.getActorTypeAccess().getDefinitionAssignment_2_1(), "rule__ActorType__DefinitionAssignment_2_1");
					put(grammarAccess.getActorInstanceDeclarationAccess().getNameAssignment_0(), "rule__ActorInstanceDeclaration__NameAssignment_0");
					put(grammarAccess.getActorInstanceDeclarationAccess().getTypeAssignment_2(), "rule__ActorInstanceDeclaration__TypeAssignment_2");
					put(grammarAccess.getDataTypeDefinitionAccess().getNameAssignment_0_1(), "rule__DataTypeDefinition__NameAssignment_0_1");
					put(grammarAccess.getDataTypeDefinitionAccess().getComponentAssignment_0_4(), "rule__DataTypeDefinition__ComponentAssignment_0_4");
					put(grammarAccess.getDataTypeDefinitionAccess().getNameAssignment_1_1(), "rule__DataTypeDefinition__NameAssignment_1_1");
					put(grammarAccess.getDataTypeDefinitionAccess().getAliasAssignment_1_4(), "rule__DataTypeDefinition__AliasAssignment_1_4");
					put(grammarAccess.getDataTypeAccess().getDefinitionSetAssignment_0_1_2_1(), "rule__DataType__DefinitionSetAssignment_0_1_2_1");
					put(grammarAccess.getDataTypeAccess().getDefinitionSetAssignment_0_2_2_1(), "rule__DataType__DefinitionSetAssignment_0_2_2_1");
					put(grammarAccess.getDataTypeAccess().getDefinitionSetAssignment_0_3_2_1(), "rule__DataType__DefinitionSetAssignment_0_3_2_1");
					put(grammarAccess.getDataTypeAccess().getDefinitionSetAssignment_0_4_2_1(), "rule__DataType__DefinitionSetAssignment_0_4_2_1");
					put(grammarAccess.getDataTypeAccess().getDefinitionSetAssignment_0_5_2_1(), "rule__DataType__DefinitionSetAssignment_0_5_2_1");
					put(grammarAccess.getDataTypeAccess().getDefinitionAssignment_0_6_1(), "rule__DataType__DefinitionAssignment_0_6_1");
					put(grammarAccess.getDataTypeSymbolDefinitionSetAccess().getElementAssignment_1(), "rule__DataTypeSymbolDefinitionSet__ElementAssignment_1");
					put(grammarAccess.getDataTypeSymbolDefinitionSetAccess().getElementAssignment_2_1(), "rule__DataTypeSymbolDefinitionSet__ElementAssignment_2_1");
					put(grammarAccess.getDataTypeSymbolDefinitionSetElementAccess().getNameAssignment_2(), "rule__DataTypeSymbolDefinitionSetElement__NameAssignment_2");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getElementAssignment_0_2(), "rule__DataTypeNumberDefinitionSet__ElementAssignment_0_2");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getElementAssignment_0_3_1(), "rule__DataTypeNumberDefinitionSet__ElementAssignment_0_3_1");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getInfAssignment_1_2(), "rule__DataTypeNumberDefinitionSet__InfAssignment_1_2");
					put(grammarAccess.getDataTypeNumberDefinitionSetAccess().getSupAssignment_1_4(), "rule__DataTypeNumberDefinitionSet__SupAssignment_1_4");
					put(grammarAccess.getDataTypeTextDefinitionSetAccess().getElementAssignment_2(), "rule__DataTypeTextDefinitionSet__ElementAssignment_2");
					put(grammarAccess.getDataTypeTextDefinitionSetAccess().getElementAssignment_3_1(), "rule__DataTypeTextDefinitionSet__ElementAssignment_3_1");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getElementAssignment_0_2(), "rule__DataTypeTimeDefinitionSet__ElementAssignment_0_2");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getElementAssignment_0_3_1(), "rule__DataTypeTimeDefinitionSet__ElementAssignment_0_3_1");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getInfAssignment_1_2(), "rule__DataTypeTimeDefinitionSet__InfAssignment_1_2");
					put(grammarAccess.getDataTypeTimeDefinitionSetAccess().getSupAssignment_1_4(), "rule__DataTypeTimeDefinitionSet__SupAssignment_1_4");
					put(grammarAccess.getDataTypeIdentifierDefinitionSetAccess().getElementAssignment_2(), "rule__DataTypeIdentifierDefinitionSet__ElementAssignment_2");
					put(grammarAccess.getDataTypeIdentifierDefinitionSetAccess().getElementAssignment_3_1(), "rule__DataTypeIdentifierDefinitionSet__ElementAssignment_3_1");
					put(grammarAccess.getDataInstanceDeclarationAccess().getNameAssignment_0(), "rule__DataInstanceDeclaration__NameAssignment_0");
					put(grammarAccess.getDataInstanceDeclarationAccess().getTypeAssignment_2(), "rule__DataInstanceDeclaration__TypeAssignment_2");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getNameAssignment_0(), "rule__InteractorTypeDefinition__NameAssignment_0");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getActorAssignment_3_0(), "rule__InteractorTypeDefinition__ActorAssignment_3_0");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getDataAssignment_3_1(), "rule__InteractorTypeDefinition__DataAssignment_3_1");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getComponentAssignment_3_2(), "rule__InteractorTypeDefinition__ComponentAssignment_3_2");
					put(grammarAccess.getInteractorTypeDefinitionAccess().getBehaviorAssignment_3_3(), "rule__InteractorTypeDefinition__BehaviorAssignment_3_3");
					put(grammarAccess.getInteractorTypeAccess().getCustomAssignment(), "rule__InteractorType__CustomAssignment");
					put(grammarAccess.getInteractorActorAccess().getNameAssignment_0(), "rule__InteractorActor__NameAssignment_0");
					put(grammarAccess.getInteractorActorAccess().getTypeAssignment_2(), "rule__InteractorActor__TypeAssignment_2");
					put(grammarAccess.getInteractorDataAccess().getNameAssignment_0(), "rule__InteractorData__NameAssignment_0");
					put(grammarAccess.getInteractorDataAccess().getTypeAssignment_2(), "rule__InteractorData__TypeAssignment_2");
					put(grammarAccess.getInteractorDataAccess().getModeAssignment_3(), "rule__InteractorData__ModeAssignment_3");
					put(grammarAccess.getInteractorDataAccess().getSourceAssignment_4_1(), "rule__InteractorData__SourceAssignment_4_1");
					put(grammarAccess.getInteractorDataAccess().getDestinationsAssignment_5_1(), "rule__InteractorData__DestinationsAssignment_5_1");
					put(grammarAccess.getInteractorSignalAliasAccess().getSourceAssignment_0(), "rule__InteractorSignalAlias__SourceAssignment_0");
					put(grammarAccess.getInteractorSignalAliasAccess().getAliasAssignment_1_1(), "rule__InteractorSignalAlias__AliasAssignment_1_1");
					put(grammarAccess.getInteractorComponentAccess().getNameAssignment_0(), "rule__InteractorComponent__NameAssignment_0");
					put(grammarAccess.getInteractorComponentAccess().getTypeAssignment_2(), "rule__InteractorComponent__TypeAssignment_2");
					put(grammarAccess.getInteractorComponentAccess().getActorsAssignment_4_1(), "rule__InteractorComponent__ActorsAssignment_4_1");
					put(grammarAccess.getInteractorComponentAccess().getActorsAssignment_4_2_1(), "rule__InteractorComponent__ActorsAssignment_4_2_1");
					put(grammarAccess.getAccessibleEntityAccess().getGenericAssignment_0(), "rule__AccessibleEntity__GenericAssignment_0");
					put(grammarAccess.getAccessibleEntityAccess().getSpecificAssignment_1(), "rule__AccessibleEntity__SpecificAssignment_1");
					put(grammarAccess.getActorAliasAccess().getSourceAssignment_0(), "rule__ActorAlias__SourceAssignment_0");
					put(grammarAccess.getActorAliasAccess().getAliasAssignment_2(), "rule__ActorAlias__AliasAssignment_2");
					put(grammarAccess.getInteractorSignalReceptionAccess().getInstanceAssignment_0_0(), "rule__InteractorSignalReception__InstanceAssignment_0_0");
					put(grammarAccess.getInteractorSignalReceptionAccess().getSourceAssignment_0_1_1(), "rule__InteractorSignalReception__SourceAssignment_0_1_1");
					put(grammarAccess.getInteractorSignalReceptionAccess().getInitAssignment_1(), "rule__InteractorSignalReception__InitAssignment_1");
					put(grammarAccess.getInteractorSignalEmissionAccess().getInstanceAssignment_0(), "rule__InteractorSignalEmission__InstanceAssignment_0");
					put(grammarAccess.getInteractorSignalEmissionAccess().getDestinationAssignment_1_1(), "rule__InteractorSignalEmission__DestinationAssignment_1_1");
					put(grammarAccess.getInteractorBehaviorAccess().getCauseAssignment_0(), "rule__InteractorBehavior__CauseAssignment_0");
					put(grammarAccess.getInteractorBehaviorAccess().getEffectAssignment_2(), "rule__InteractorBehavior__EffectAssignment_2");
					put(grammarAccess.getInteractorBehaviorOnCauseAccess().getEventAssignment_1(), "rule__InteractorBehaviorOnCause__EventAssignment_1");
					put(grammarAccess.getInteractorBehaviorOnCauseAccess().getGuardAssignment_2_1(), "rule__InteractorBehaviorOnCause__GuardAssignment_2_1");
					put(grammarAccess.getInteractorBehaviorWhenCauseAccess().getConditionAssignment_1(), "rule__InteractorBehaviorWhenCause__ConditionAssignment_1");
					put(grammarAccess.getInteractorBehaviorWhenCauseAccess().getGuardAssignment_2_1(), "rule__InteractorBehaviorWhenCause__GuardAssignment_2_1");
					put(grammarAccess.getInteractorBehaviorAlwaysEffectAccess().getTargetAssignment_1(), "rule__InteractorBehaviorAlwaysEffect__TargetAssignment_1");
					put(grammarAccess.getInteractorBehaviorAlwaysEffectAccess().getValueAssignment_3(), "rule__InteractorBehaviorAlwaysEffect__ValueAssignment_3");
					put(grammarAccess.getInteractorBehaviorSetEffectAccess().getTargetAssignment_1(), "rule__InteractorBehaviorSetEffect__TargetAssignment_1");
					put(grammarAccess.getInteractorBehaviorSetEffectAccess().getValueAssignment_3(), "rule__InteractorBehaviorSetEffect__ValueAssignment_3");
					put(grammarAccess.getInteractorBehaviorTriggerEffectAccess().getTargetAssignment_1(), "rule__InteractorBehaviorTriggerEffect__TargetAssignment_1");
					put(grammarAccess.getInteractorBehaviorTriggerEffectAccess().getValueAssignment_3(), "rule__InteractorBehaviorTriggerEffect__ValueAssignment_3");
					put(grammarAccess.getExpressionOrAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionOr__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionOrAccess().getRightOperandAssignment_1_1(), "rule__ExpressionOr__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionAndAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionAnd__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionAndAccess().getRightOperandAssignment_1_1(), "rule__ExpressionAnd__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionEqualityAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionEquality__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionEqualityAccess().getRightOperandAssignment_1_1(), "rule__ExpressionEquality__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionCompareAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionCompare__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionCompareAccess().getRightOperandAssignment_1_1(), "rule__ExpressionCompare__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionOtherAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionOther__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionOtherAccess().getRightOperandAssignment_1_1(), "rule__ExpressionOther__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionAdditionAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionAddition__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionAdditionAccess().getRightOperandAssignment_1_1(), "rule__ExpressionAddition__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionMultiplicationAccess().getFeatureAssignment_1_0_0_1(), "rule__ExpressionMultiplication__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getExpressionMultiplicationAccess().getRightOperandAssignment_1_1(), "rule__ExpressionMultiplication__RightOperandAssignment_1_1");
					put(grammarAccess.getExpressionUnaryAccess().getFeatureAssignment_0_1(), "rule__ExpressionUnary__FeatureAssignment_0_1");
					put(grammarAccess.getExpressionUnaryAccess().getOperandAssignment_0_2(), "rule__ExpressionUnary__OperandAssignment_0_2");
					put(grammarAccess.getExpressionLiteralAccess().getDataAssignment_7_1(), "rule__ExpressionLiteral__DataAssignment_7_1");
					put(grammarAccess.getExpressionLiteralSetAccess().getElementsAssignment_2_0(), "rule__ExpressionLiteralSet__ElementsAssignment_2_0");
					put(grammarAccess.getExpressionLiteralSetAccess().getElementsAssignment_2_1_1(), "rule__ExpressionLiteralSet__ElementsAssignment_2_1_1");
					put(grammarAccess.getExpressionLiteralListAccess().getElementsAssignment_2_0(), "rule__ExpressionLiteralList__ElementsAssignment_2_0");
					put(grammarAccess.getExpressionLiteralListAccess().getElementsAssignment_2_1_1(), "rule__ExpressionLiteralList__ElementsAssignment_2_1_1");
					put(grammarAccess.getExpressionIfAccess().getIfAssignment_3(), "rule__ExpressionIf__IfAssignment_3");
					put(grammarAccess.getExpressionIfAccess().getThenAssignment_5(), "rule__ExpressionIf__ThenAssignment_5");
					put(grammarAccess.getExpressionIfAccess().getElseAssignment_6_1(), "rule__ExpressionIf__ElseAssignment_6_1");
					put(grammarAccess.getExpressionSwitchAccess().getSwitchAssignment_3(), "rule__ExpressionSwitch__SwitchAssignment_3");
					put(grammarAccess.getExpressionSwitchAccess().getCaseAssignment_5(), "rule__ExpressionSwitch__CaseAssignment_5");
					put(grammarAccess.getExpressionSwitchAccess().getDefaultAssignment_6_2(), "rule__ExpressionSwitch__DefaultAssignment_6_2");
					put(grammarAccess.getExpressionCaseAccess().getCaseAssignment_1(), "rule__ExpressionCase__CaseAssignment_1");
					put(grammarAccess.getExpressionCaseAccess().getThenAssignment_3(), "rule__ExpressionCase__ThenAssignment_3");
					put(grammarAccess.getExpressionForEachAccess().getForExpressionAssignment_4(), "rule__ExpressionForEach__ForExpressionAssignment_4");
					put(grammarAccess.getExpressionForEachAccess().getEachExpressionAssignment_6(), "rule__ExpressionForEach__EachExpressionAssignment_6");
					put(grammarAccess.getExpressionFunctionCallAccess().getFunctionAssignment_1(), "rule__ExpressionFunctionCall__FunctionAssignment_1");
					put(grammarAccess.getExpressionFunctionCallAccess().getArgumentsAssignment_3(), "rule__ExpressionFunctionCall__ArgumentsAssignment_3");
					put(grammarAccess.getExpressionFunctionCallAccess().getArgumentsAssignment_4_1(), "rule__ExpressionFunctionCall__ArgumentsAssignment_4_1");
					put(grammarAccess.getLiteralBooleanAccess().getIsTrueAssignment_1_1(), "rule__LiteralBoolean__IsTrueAssignment_1_1");
					put(grammarAccess.getLiteralNumberAccess().getValueAssignment_1(), "rule__LiteralNumber__ValueAssignment_1");
					put(grammarAccess.getLiteralTextAccess().getValueAssignment_1(), "rule__LiteralText__ValueAssignment_1");
					put(grammarAccess.getLiteralEnumAccess().getValueAssignment_2(), "rule__LiteralEnum__ValueAssignment_2");
					put(grammarAccess.getLiteralTimeAccess().getNowAssignment_0_1(), "rule__LiteralTime__NowAssignment_0_1");
					put(grammarAccess.getLiteralTimeAccess().getYearAssignment_1_1_0(), "rule__LiteralTime__YearAssignment_1_1_0");
					put(grammarAccess.getLiteralTimeAccess().getMonthAssignment_1_2_0(), "rule__LiteralTime__MonthAssignment_1_2_0");
					put(grammarAccess.getLiteralTimeAccess().getDayAssignment_1_3_0(), "rule__LiteralTime__DayAssignment_1_3_0");
					put(grammarAccess.getLiteralTimeAccess().getHourAssignment_1_4_0(), "rule__LiteralTime__HourAssignment_1_4_0");
					put(grammarAccess.getLiteralTimeAccess().getMinuteAssignment_1_5_0(), "rule__LiteralTime__MinuteAssignment_1_5_0");
					put(grammarAccess.getLiteralTimeAccess().getSecondAssignment_1_6_0(), "rule__LiteralTime__SecondAssignment_1_6_0");
					put(grammarAccess.getLiteralTimeAccess().getMonthAssignment_2_1_0(), "rule__LiteralTime__MonthAssignment_2_1_0");
					put(grammarAccess.getLiteralTimeAccess().getDayAssignment_2_2_0(), "rule__LiteralTime__DayAssignment_2_2_0");
					put(grammarAccess.getLiteralTimeAccess().getHourAssignment_2_3_0(), "rule__LiteralTime__HourAssignment_2_3_0");
					put(grammarAccess.getLiteralTimeAccess().getMinuteAssignment_2_4_0(), "rule__LiteralTime__MinuteAssignment_2_4_0");
					put(grammarAccess.getLiteralTimeAccess().getSecondAssignment_2_5_0(), "rule__LiteralTime__SecondAssignment_2_5_0");
					put(grammarAccess.getLiteralTimeAccess().getDayAssignment_3_1_0(), "rule__LiteralTime__DayAssignment_3_1_0");
					put(grammarAccess.getLiteralTimeAccess().getHourAssignment_3_2_0(), "rule__LiteralTime__HourAssignment_3_2_0");
					put(grammarAccess.getLiteralTimeAccess().getMinuteAssignment_3_3_0(), "rule__LiteralTime__MinuteAssignment_3_3_0");
					put(grammarAccess.getLiteralTimeAccess().getSecondAssignment_3_4_0(), "rule__LiteralTime__SecondAssignment_3_4_0");
					put(grammarAccess.getLiteralTimeAccess().getHourAssignment_4_1_0(), "rule__LiteralTime__HourAssignment_4_1_0");
					put(grammarAccess.getLiteralTimeAccess().getMinuteAssignment_4_2_0(), "rule__LiteralTime__MinuteAssignment_4_2_0");
					put(grammarAccess.getLiteralTimeAccess().getSecondAssignment_4_3_0(), "rule__LiteralTime__SecondAssignment_4_3_0");
					put(grammarAccess.getLiteralTimeAccess().getMinuteAssignment_5_1_0(), "rule__LiteralTime__MinuteAssignment_5_1_0");
					put(grammarAccess.getLiteralTimeAccess().getSecondAssignment_5_2_0(), "rule__LiteralTime__SecondAssignment_5_2_0");
					put(grammarAccess.getLiteralTimeAccess().getSecondAssignment_6_1_0(), "rule__LiteralTime__SecondAssignment_6_1_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser typedParser = (com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser) parser;
			typedParser.entryRuleLilModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public LilGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LilGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
