/*
* generated by Xtext
*/
package com.crubier.lil.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.crubier.lil.services.LilGrammarAccess;

public class LilParser extends AbstractContentAssistParser {
	
	@Inject
	private LilGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser createParser() {
		com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser result = new com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getLilModelAccess().getAlternatives(), "rule__LilModel__Alternatives");
					put(grammarAccess.getInteractorAccess().getAlternatives_3(), "rule__Interactor__Alternatives_3");
					put(grammarAccess.getAccessibleEntityAccess().getAlternatives(), "rule__AccessibleEntity__Alternatives");
					put(grammarAccess.getGenericEntityAccess().getAlternatives(), "rule__GenericEntity__Alternatives");
					put(grammarAccess.getEntityAccess().getAlternatives(), "rule__Entity__Alternatives");
					put(grammarAccess.getSignalReceptionAccess().getAlternatives(), "rule__SignalReception__Alternatives");
					put(grammarAccess.getSignalModeAccess().getAlternatives(), "rule__SignalMode__Alternatives");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getDataTypeBaseAccess().getAlternatives(), "rule__DataTypeBase__Alternatives");
					put(grammarAccess.getCauseAccess().getAlternatives(), "rule__Cause__Alternatives");
					put(grammarAccess.getEffectAccess().getAlternatives(), "rule__Effect__Alternatives");
					put(grammarAccess.getOpEqualityAccess().getAlternatives(), "rule__OpEquality__Alternatives");
					put(grammarAccess.getOpCompareAccess().getAlternatives(), "rule__OpCompare__Alternatives");
					put(grammarAccess.getOpOtherAccess().getAlternatives(), "rule__OpOther__Alternatives");
					put(grammarAccess.getOpAddAccess().getAlternatives(), "rule__OpAdd__Alternatives");
					put(grammarAccess.getOpMultiAccess().getAlternatives(), "rule__OpMulti__Alternatives");
					put(grammarAccess.getXUnaryOperationAccess().getAlternatives(), "rule__XUnaryOperation__Alternatives");
					put(grammarAccess.getOpUnaryAccess().getAlternatives(), "rule__OpUnary__Alternatives");
					put(grammarAccess.getXPrimaryExpressionAccess().getAlternatives(), "rule__XPrimaryExpression__Alternatives");
					put(grammarAccess.getXLiteralAccess().getAlternatives(), "rule__XLiteral__Alternatives");
					put(grammarAccess.getXCollectionLiteralAccess().getAlternatives(), "rule__XCollectionLiteral__Alternatives");
					put(grammarAccess.getBuiltInFunctionAccess().getAlternatives(), "rule__BuiltInFunction__Alternatives");
					put(grammarAccess.getXBooleanLiteralAccess().getAlternatives_1(), "rule__XBooleanLiteral__Alternatives_1");
					put(grammarAccess.getInteractorAccess().getGroup(), "rule__Interactor__Group__0");
					put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
					put(grammarAccess.getActorAliasAccess().getGroup(), "rule__ActorAlias__Group__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_3(), "rule__Component__Group_3__0");
					put(grammarAccess.getComponentAccess().getGroup_3_2(), "rule__Component__Group_3_2__0");
					put(grammarAccess.getSignalReceptionAccess().getGroup_0(), "rule__SignalReception__Group_0__0");
					put(grammarAccess.getSignalReceptionAccess().getGroup_0_1(), "rule__SignalReception__Group_0_1__0");
					put(grammarAccess.getSignalEmissionAccess().getGroup(), "rule__SignalEmission__Group__0");
					put(grammarAccess.getSignalEmissionAccess().getGroup_1(), "rule__SignalEmission__Group_1__0");
					put(grammarAccess.getSignalAccess().getGroup(), "rule__Signal__Group__0");
					put(grammarAccess.getSignalAccess().getGroup_4(), "rule__Signal__Group_4__0");
					put(grammarAccess.getSignalAccess().getGroup_5(), "rule__Signal__Group_5__0");
					put(grammarAccess.getSignalAliasAccess().getGroup(), "rule__SignalAlias__Group__0");
					put(grammarAccess.getSignalAliasAccess().getGroup_1(), "rule__SignalAlias__Group_1__0");
					put(grammarAccess.getDataTypeCompoundAccess().getGroup(), "rule__DataTypeCompound__Group__0");
					put(grammarAccess.getDataTypeCompoundFieldAccess().getGroup(), "rule__DataTypeCompoundField__Group__0");
					put(grammarAccess.getBehaviorAccess().getGroup(), "rule__Behavior__Group__0");
					put(grammarAccess.getOnCauseAccess().getGroup(), "rule__OnCause__Group__0");
					put(grammarAccess.getOnCauseAccess().getGroup_2(), "rule__OnCause__Group_2__0");
					put(grammarAccess.getWhenCauseAccess().getGroup(), "rule__WhenCause__Group__0");
					put(grammarAccess.getWhenCauseAccess().getGroup_2(), "rule__WhenCause__Group_2__0");
					put(grammarAccess.getAlwaysEffectAccess().getGroup(), "rule__AlwaysEffect__Group__0");
					put(grammarAccess.getSetEffectAccess().getGroup(), "rule__SetEffect__Group__0");
					put(grammarAccess.getTriggerEffectAccess().getGroup(), "rule__TriggerEffect__Group__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup(), "rule__XOrExpression__Group__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup_1(), "rule__XOrExpression__Group_1__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup_1_0(), "rule__XOrExpression__Group_1_0__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup_1_0_0(), "rule__XOrExpression__Group_1_0_0__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup(), "rule__XAndExpression__Group__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup_1(), "rule__XAndExpression__Group_1__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup_1_0(), "rule__XAndExpression__Group_1_0__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup_1_0_0(), "rule__XAndExpression__Group_1_0_0__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup(), "rule__XEqualityExpression__Group__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup_1(), "rule__XEqualityExpression__Group_1__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup_1_0(), "rule__XEqualityExpression__Group_1_0__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup_1_0_0(), "rule__XEqualityExpression__Group_1_0_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup(), "rule__XRelationalExpression__Group__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1(), "rule__XRelationalExpression__Group_1__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_0(), "rule__XRelationalExpression__Group_1_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_0_0(), "rule__XRelationalExpression__Group_1_0_0__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup(), "rule__XOtherOperatorExpression__Group__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup_1(), "rule__XOtherOperatorExpression__Group_1__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup_1_0(), "rule__XOtherOperatorExpression__Group_1_0__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup_1_0_0(), "rule__XOtherOperatorExpression__Group_1_0_0__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup(), "rule__XAdditiveExpression__Group__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup_1(), "rule__XAdditiveExpression__Group_1__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup_1_0(), "rule__XAdditiveExpression__Group_1_0__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup_1_0_0(), "rule__XAdditiveExpression__Group_1_0_0__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup(), "rule__XMultiplicativeExpression__Group__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup_1(), "rule__XMultiplicativeExpression__Group_1__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup_1_0(), "rule__XMultiplicativeExpression__Group_1_0__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup_1_0_0(), "rule__XMultiplicativeExpression__Group_1_0_0__0");
					put(grammarAccess.getXUnaryOperationAccess().getGroup_0(), "rule__XUnaryOperation__Group_0__0");
					put(grammarAccess.getXSetLiteralAccess().getGroup(), "rule__XSetLiteral__Group__0");
					put(grammarAccess.getXSetLiteralAccess().getGroup_2(), "rule__XSetLiteral__Group_2__0");
					put(grammarAccess.getXSetLiteralAccess().getGroup_2_1(), "rule__XSetLiteral__Group_2_1__0");
					put(grammarAccess.getXListLiteralAccess().getGroup(), "rule__XListLiteral__Group__0");
					put(grammarAccess.getXListLiteralAccess().getGroup_2(), "rule__XListLiteral__Group_2__0");
					put(grammarAccess.getXListLiteralAccess().getGroup_2_1(), "rule__XListLiteral__Group_2_1__0");
					put(grammarAccess.getXParenthesizedExpressionAccess().getGroup(), "rule__XParenthesizedExpression__Group__0");
					put(grammarAccess.getXIfExpressionAccess().getGroup(), "rule__XIfExpression__Group__0");
					put(grammarAccess.getXIfExpressionAccess().getGroup_6(), "rule__XIfExpression__Group_6__0");
					put(grammarAccess.getXSwitchExpressionAccess().getGroup(), "rule__XSwitchExpression__Group__0");
					put(grammarAccess.getXSwitchExpressionAccess().getGroup_6(), "rule__XSwitchExpression__Group_6__0");
					put(grammarAccess.getXCasePartAccess().getGroup(), "rule__XCasePart__Group__0");
					put(grammarAccess.getXForEachExpressionAccess().getGroup(), "rule__XForEachExpression__Group__0");
					put(grammarAccess.getXFunctionCallExpressionAccess().getGroup(), "rule__XFunctionCallExpression__Group__0");
					put(grammarAccess.getXFunctionCallExpressionAccess().getGroup_4(), "rule__XFunctionCallExpression__Group_4__0");
					put(grammarAccess.getXBooleanLiteralAccess().getGroup(), "rule__XBooleanLiteral__Group__0");
					put(grammarAccess.getXNullLiteralAccess().getGroup(), "rule__XNullLiteral__Group__0");
					put(grammarAccess.getXNumberLiteralAccess().getGroup(), "rule__XNumberLiteral__Group__0");
					put(grammarAccess.getXStringLiteralAccess().getGroup(), "rule__XStringLiteral__Group__0");
					put(grammarAccess.getNUMBERAccess().getGroup(), "rule__NUMBER__Group__0");
					put(grammarAccess.getNUMBERAccess().getGroup_1(), "rule__NUMBER__Group_1__0");
					put(grammarAccess.getLilModelAccess().getInteractorsAssignment_0(), "rule__LilModel__InteractorsAssignment_0");
					put(grammarAccess.getLilModelAccess().getDataTypesAssignment_1(), "rule__LilModel__DataTypesAssignment_1");
					put(grammarAccess.getInteractorAccess().getNameAssignment_1(), "rule__Interactor__NameAssignment_1");
					put(grammarAccess.getInteractorAccess().getEntitiesAssignment_3_0(), "rule__Interactor__EntitiesAssignment_3_0");
					put(grammarAccess.getInteractorAccess().getSignalsAssignment_3_1(), "rule__Interactor__SignalsAssignment_3_1");
					put(grammarAccess.getInteractorAccess().getBehaviorsAssignment_3_2(), "rule__Interactor__BehaviorsAssignment_3_2");
					put(grammarAccess.getAccessibleEntityAccess().getGenericAssignment_0(), "rule__AccessibleEntity__GenericAssignment_0");
					put(grammarAccess.getAccessibleEntityAccess().getSpecificAssignment_1(), "rule__AccessibleEntity__SpecificAssignment_1");
					put(grammarAccess.getActorAccess().getNameAssignment_0(), "rule__Actor__NameAssignment_0");
					put(grammarAccess.getActorAliasAccess().getSourceAssignment_0(), "rule__ActorAlias__SourceAssignment_0");
					put(grammarAccess.getActorAliasAccess().getAliasAssignment_2(), "rule__ActorAlias__AliasAssignment_2");
					put(grammarAccess.getComponentAccess().getNameAssignment_0(), "rule__Component__NameAssignment_0");
					put(grammarAccess.getComponentAccess().getInteractorAssignment_2(), "rule__Component__InteractorAssignment_2");
					put(grammarAccess.getComponentAccess().getActorsAssignment_3_1(), "rule__Component__ActorsAssignment_3_1");
					put(grammarAccess.getComponentAccess().getActorsAssignment_3_2_1(), "rule__Component__ActorsAssignment_3_2_1");
					put(grammarAccess.getSignalReceptionAccess().getInstanceAssignment_0_0(), "rule__SignalReception__InstanceAssignment_0_0");
					put(grammarAccess.getSignalReceptionAccess().getSourceAssignment_0_1_1(), "rule__SignalReception__SourceAssignment_0_1_1");
					put(grammarAccess.getSignalReceptionAccess().getInitAssignment_1(), "rule__SignalReception__InitAssignment_1");
					put(grammarAccess.getSignalEmissionAccess().getInstanceAssignment_0(), "rule__SignalEmission__InstanceAssignment_0");
					put(grammarAccess.getSignalEmissionAccess().getDestinationAssignment_1_1(), "rule__SignalEmission__DestinationAssignment_1_1");
					put(grammarAccess.getSignalAccess().getNameAssignment_0(), "rule__Signal__NameAssignment_0");
					put(grammarAccess.getSignalAccess().getTypeAssignment_2(), "rule__Signal__TypeAssignment_2");
					put(grammarAccess.getSignalAccess().getModeAssignment_3(), "rule__Signal__ModeAssignment_3");
					put(grammarAccess.getSignalAccess().getSourceAssignment_4_1(), "rule__Signal__SourceAssignment_4_1");
					put(grammarAccess.getSignalAccess().getDestinationsAssignment_5_1(), "rule__Signal__DestinationsAssignment_5_1");
					put(grammarAccess.getSignalAliasAccess().getSourceAssignment_0(), "rule__SignalAlias__SourceAssignment_0");
					put(grammarAccess.getSignalAliasAccess().getAliasAssignment_1_1(), "rule__SignalAlias__AliasAssignment_1_1");
					put(grammarAccess.getDataTypeAccess().getBaseAssignment_0(), "rule__DataType__BaseAssignment_0");
					put(grammarAccess.getDataTypeAccess().getCompoundAssignment_1(), "rule__DataType__CompoundAssignment_1");
					put(grammarAccess.getDataTypeCompoundAccess().getNameAssignment_1(), "rule__DataTypeCompound__NameAssignment_1");
					put(grammarAccess.getDataTypeCompoundAccess().getFieldsAssignment_3(), "rule__DataTypeCompound__FieldsAssignment_3");
					put(grammarAccess.getDataTypeCompoundFieldAccess().getNameAssignment_0(), "rule__DataTypeCompoundField__NameAssignment_0");
					put(grammarAccess.getDataTypeCompoundFieldAccess().getTypeAssignment_2(), "rule__DataTypeCompoundField__TypeAssignment_2");
					put(grammarAccess.getBehaviorAccess().getCauseAssignment_0(), "rule__Behavior__CauseAssignment_0");
					put(grammarAccess.getBehaviorAccess().getEffectsAssignment_2(), "rule__Behavior__EffectsAssignment_2");
					put(grammarAccess.getOnCauseAccess().getEventAssignment_1(), "rule__OnCause__EventAssignment_1");
					put(grammarAccess.getOnCauseAccess().getGuardAssignment_2_1(), "rule__OnCause__GuardAssignment_2_1");
					put(grammarAccess.getWhenCauseAccess().getConditionAssignment_1(), "rule__WhenCause__ConditionAssignment_1");
					put(grammarAccess.getWhenCauseAccess().getGuardAssignment_2_1(), "rule__WhenCause__GuardAssignment_2_1");
					put(grammarAccess.getAlwaysEffectAccess().getTargetAssignment_1(), "rule__AlwaysEffect__TargetAssignment_1");
					put(grammarAccess.getAlwaysEffectAccess().getValueAssignment_3(), "rule__AlwaysEffect__ValueAssignment_3");
					put(grammarAccess.getSetEffectAccess().getTargetAssignment_1(), "rule__SetEffect__TargetAssignment_1");
					put(grammarAccess.getSetEffectAccess().getValueAssignment_3(), "rule__SetEffect__ValueAssignment_3");
					put(grammarAccess.getTriggerEffectAccess().getTargetAssignment_1(), "rule__TriggerEffect__TargetAssignment_1");
					put(grammarAccess.getTriggerEffectAccess().getValueAssignment_3(), "rule__TriggerEffect__ValueAssignment_3");
					put(grammarAccess.getXOrExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XOrExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXOrExpressionAccess().getRightOperandAssignment_1_1(), "rule__XOrExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXAndExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XAndExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXAndExpressionAccess().getRightOperandAssignment_1_1(), "rule__XAndExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXEqualityExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XEqualityExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXEqualityExpressionAccess().getRightOperandAssignment_1_1(), "rule__XEqualityExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXRelationalExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XRelationalExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXRelationalExpressionAccess().getRightOperandAssignment_1_1(), "rule__XRelationalExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XOtherOperatorExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getRightOperandAssignment_1_1(), "rule__XOtherOperatorExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXAdditiveExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XAdditiveExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXAdditiveExpressionAccess().getRightOperandAssignment_1_1(), "rule__XAdditiveExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XMultiplicativeExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getRightOperandAssignment_1_1(), "rule__XMultiplicativeExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXUnaryOperationAccess().getFeatureAssignment_0_1(), "rule__XUnaryOperation__FeatureAssignment_0_1");
					put(grammarAccess.getXUnaryOperationAccess().getOperandAssignment_0_2(), "rule__XUnaryOperation__OperandAssignment_0_2");
					put(grammarAccess.getXSetLiteralAccess().getElementsAssignment_2_0(), "rule__XSetLiteral__ElementsAssignment_2_0");
					put(grammarAccess.getXSetLiteralAccess().getElementsAssignment_2_1_1(), "rule__XSetLiteral__ElementsAssignment_2_1_1");
					put(grammarAccess.getXListLiteralAccess().getElementsAssignment_2_0(), "rule__XListLiteral__ElementsAssignment_2_0");
					put(grammarAccess.getXListLiteralAccess().getElementsAssignment_2_1_1(), "rule__XListLiteral__ElementsAssignment_2_1_1");
					put(grammarAccess.getXIfExpressionAccess().getIfAssignment_3(), "rule__XIfExpression__IfAssignment_3");
					put(grammarAccess.getXIfExpressionAccess().getThenAssignment_5(), "rule__XIfExpression__ThenAssignment_5");
					put(grammarAccess.getXIfExpressionAccess().getElseAssignment_6_1(), "rule__XIfExpression__ElseAssignment_6_1");
					put(grammarAccess.getXSwitchExpressionAccess().getSwitchAssignment_3(), "rule__XSwitchExpression__SwitchAssignment_3");
					put(grammarAccess.getXSwitchExpressionAccess().getCasesAssignment_5(), "rule__XSwitchExpression__CasesAssignment_5");
					put(grammarAccess.getXSwitchExpressionAccess().getDefaultAssignment_6_2(), "rule__XSwitchExpression__DefaultAssignment_6_2");
					put(grammarAccess.getXCasePartAccess().getCaseAssignment_1(), "rule__XCasePart__CaseAssignment_1");
					put(grammarAccess.getXCasePartAccess().getThenAssignment_3(), "rule__XCasePart__ThenAssignment_3");
					put(grammarAccess.getXForEachExpressionAccess().getForExpressionAssignment_4(), "rule__XForEachExpression__ForExpressionAssignment_4");
					put(grammarAccess.getXForEachExpressionAccess().getEachExpressionAssignment_6(), "rule__XForEachExpression__EachExpressionAssignment_6");
					put(grammarAccess.getXFunctionCallExpressionAccess().getFunctionAssignment_1(), "rule__XFunctionCallExpression__FunctionAssignment_1");
					put(grammarAccess.getXFunctionCallExpressionAccess().getArgumentsAssignment_3(), "rule__XFunctionCallExpression__ArgumentsAssignment_3");
					put(grammarAccess.getXFunctionCallExpressionAccess().getArgumentsAssignment_4_1(), "rule__XFunctionCallExpression__ArgumentsAssignment_4_1");
					put(grammarAccess.getXBooleanLiteralAccess().getIsTrueAssignment_1_1(), "rule__XBooleanLiteral__IsTrueAssignment_1_1");
					put(grammarAccess.getXNumberLiteralAccess().getValueAssignment_1(), "rule__XNumberLiteral__ValueAssignment_1");
					put(grammarAccess.getXStringLiteralAccess().getValueAssignment_1(), "rule__XStringLiteral__ValueAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser typedParser = (com.crubier.lil.ui.contentassist.antlr.internal.InternalLilParser) parser;
			typedParser.entryRuleLilModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public LilGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LilGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
