/**
 * generated by Xtext
 */
package com.crubier.lil.ui.contentassist;

import com.crubier.lil.ui.contentassist.AbstractLilProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LilProposalProvider extends AbstractLilProposalProvider {
}
