/*
 * generated by Xtext
 */
package com.crubier.lil.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.crubier.lil.ui.internal.LilActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LilExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LilActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LilActivator.getInstance().getInjector(LilActivator.COM_CRUBIER_LIL_LIL);
	}
	
}
