/*
 * generated by Xtext
 */
package com.crubier.lil.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLilValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.crubier.lil.lil.LilPackage.eINSTANCE);
		return result;
	}
}
