/**
 * generated by Xtext
 */
package com.crubier.lil.validation;

import com.crubier.lil.validation.AbstractLilValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LilValidator extends AbstractLilValidator {
  public final static String INVALID_NAME = "invalidName";
}
